//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeptoServer.Ftp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FtpCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FtpCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeptoServer.Ftp.FtpCommands", typeof(FtpCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOR.
        /// </summary>
        internal static string AbortFileTransfer {
            get {
                return ResourceManager.GetString("AbortFileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLO.
        /// </summary>
        internal static string Allocate {
            get {
                return ResourceManager.GetString("Allocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPE.
        /// </summary>
        internal static string AppendFile {
            get {
                return ResourceManager.GetString("AppendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDUP.
        /// </summary>
        internal static string ChangeDirectoryUp {
            get {
                return ResourceManager.GetString("ChangeDirectoryUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XCUP.
        /// </summary>
        internal static string ChangeDirectoryUpExtended {
            get {
                return ResourceManager.GetString("ChangeDirectoryUpExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWD.
        /// </summary>
        internal static string ChangeWorkingDirectory {
            get {
                return ResourceManager.GetString("ChangeWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XCWD.
        /// </summary>
        internal static string ChangeWorkingDirectoryExtended {
            get {
                return ResourceManager.GetString("ChangeWorkingDirectoryExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELE.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEAT.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRU.
        /// </summary>
        internal static string FileStructure {
            get {
                return ResourceManager.GetString("FileStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLST.
        /// </summary>
        internal static string ListFileNames {
            get {
                return ResourceManager.GetString("ListFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST.
        /// </summary>
        internal static string ListFiles {
            get {
                return ResourceManager.GetString("ListFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKD.
        /// </summary>
        internal static string MakeDirectory {
            get {
                return ResourceManager.GetString("MakeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMKD.
        /// </summary>
        internal static string MakeDirectoryExtended {
            get {
                return ResourceManager.GetString("MakeDirectoryExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDMT.
        /// </summary>
        internal static string ModifiedTime {
            get {
                return ResourceManager.GetString("ModifiedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOOP.
        /// </summary>
        internal static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTS.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASV.
        /// </summary>
        internal static string PassiveMode {
            get {
                return ResourceManager.GetString("PassiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORT.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWD.
        /// </summary>
        internal static string PrintWorkingDirectory {
            get {
                return ResourceManager.GetString("PrintWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPWD.
        /// </summary>
        internal static string PrintWorkingDirectoryExtended {
            get {
                return ResourceManager.GetString("PrintWorkingDirectoryExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REIN.
        /// </summary>
        internal static string Reinitialize {
            get {
                return ResourceManager.GetString("Reinitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMD.
        /// </summary>
        internal static string RemoveDirectory {
            get {
                return ResourceManager.GetString("RemoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRMD.
        /// </summary>
        internal static string RemoveDirectoryExtended {
            get {
                return ResourceManager.GetString("RemoveDirectoryExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNFR.
        /// </summary>
        internal static string RenameFrom {
            get {
                return ResourceManager.GetString("RenameFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNTO.
        /// </summary>
        internal static string RenameTo {
            get {
                return ResourceManager.GetString("RenameTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST.
        /// </summary>
        internal static string RestartFileTransfer {
            get {
                return ResourceManager.GetString("RestartFileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETR.
        /// </summary>
        internal static string RetrieveFile {
            get {
                return ResourceManager.GetString("RetrieveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOR.
        /// </summary>
        internal static string StoreFile {
            get {
                return ResourceManager.GetString("StoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYST.
        /// </summary>
        internal static string SystemType {
            get {
                return ResourceManager.GetString("SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODE.
        /// </summary>
        internal static string TransferMode {
            get {
                return ResourceManager.GetString("TransferMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string TransferType {
            get {
                return ResourceManager.GetString("TransferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
