//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeptoServer.Ftp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FtpMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FtpMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeptoServer.Ftp.FtpMessages", typeof(FtpMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open data connection.
        /// </summary>
        internal static string CanNotOpenDataChannel {
            get {
                return ResourceManager.GetString("CanNotOpenDataChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions supported:.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string FileActionOk {
            get {
                return ResourceManager.GetString("FileActionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need more info.
        /// </summary>
        internal static string FileMoreInfoRequired {
            get {
                return ResourceManager.GetString("FileMoreInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File unavailable.
        /// </summary>
        internal static string FileUnavailable {
            get {
                return ResourceManager.GetString("FileUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        internal static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        internal static string NotEnoughSpace {
            get {
                return ResourceManager.GetString("NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not supported.
        /// </summary>
        internal static string NotImplementedForParameter {
            get {
                return ResourceManager.GetString("NotImplementedForParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File status okay; about to open data connection..
        /// </summary>
        internal static string OpenningDataChannel {
            get {
                return ResourceManager.GetString("OpenningDataChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering Passive Mode ({0},{1},{2},{3},{4},{5}).
        /// </summary>
        internal static string PassiveModeFormat {
            get {
                return ResourceManager.GetString("PassiveModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ServiceReady {
            get {
                return ResourceManager.GetString("ServiceReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIX Type: L8.
        /// </summary>
        internal static string SystemType {
            get {
                return ResourceManager.GetString("SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Complete.
        /// </summary>
        internal static string TransferComplete {
            get {
                return ResourceManager.GetString("TransferComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string UserOk {
            get {
                return ResourceManager.GetString("UserOk", resourceCulture);
            }
        }
    }
}
