//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeptoServer.Ftp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeptoServer.Ftp.TraceResources", typeof(TraceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to client at {0}.
        /// </summary>
        internal static string ActiveModeConnectedFormat {
            get {
                return ResourceManager.GetString("ActiveModeConnectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to client at {0}....
        /// </summary>
        internal static string ActiveModeConnectingFormat {
            get {
                return ResourceManager.GetString("ActiveModeConnectingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTV.
        /// </summary>
        internal static string ActiveModeLoggerScope {
            get {
                return ResourceManager.GetString("ActiveModeLoggerScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is not supported.
        /// </summary>
        internal static string CommandNotSupported {
            get {
                return ResourceManager.GetString("CommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolved public IP address for the host &quot;{0}&quot;: {1}. Socket address &quot;{2}&quot; will be used as an address of the server..
        /// </summary>
        internal static string CouldNotResolvePublicAddressFormat {
            get {
                return ResourceManager.GetString("CouldNotResolvePublicAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created directory &quot;{0}&quot;.
        /// </summary>
        internal static string CreatedDirectoryFormat {
            get {
                return ResourceManager.GetString("CreatedDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted directory &quot;{0}&quot;.
        /// </summary>
        internal static string DeletedDirectoryFormat {
            get {
                return ResourceManager.GetString("DeletedDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted file &quot;{0}&quot;.
        /// </summary>
        internal static string DeletedFileFormat {
            get {
                return ResourceManager.GetString("DeletedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored file &quot;{0}&quot;.
        /// </summary>
        internal static string FileStoredFormat {
            get {
                return ResourceManager.GetString("FileStoredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt for user &quot;{0}&quot; with password &quot;{1}&quot;.
        /// </summary>
        internal static string InvalidLoginAttemptFormat {
            get {
                return ResourceManager.GetString("InvalidLoginAttemptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connected from {0}.
        /// </summary>
        internal static string PassiveModeConnectedFormat {
            get {
                return ResourceManager.GetString("PassiveModeConnectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting new connections.
        /// </summary>
        internal static string PassiveModeConnecting {
            get {
                return ResourceManager.GetString("PassiveModeConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASV.
        /// </summary>
        internal static string PassiveModeLoggerScope {
            get {
                return ResourceManager.GetString("PassiveModeLoggerScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed directory &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        internal static string RenamedDirectoryFormat {
            get {
                return ResourceManager.GetString("RenamedDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed file &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        internal static string RenamedFileFormat {
            get {
                return ResourceManager.GetString("RenamedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved file &quot;{0}&quot;.
        /// </summary>
        internal static string RetrievedFileFormat {
            get {
                return ResourceManager.GetString("RetrievedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; logged in.
        /// </summary>
        internal static string UserLoggedInFormat {
            get {
                return ResourceManager.GetString("UserLoggedInFormat", resourceCulture);
            }
        }
    }
}
